# Generated by Django 6.1 on 2026-09-07 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_table_number_alter_order_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='encrypted_phone',
            field=models.CharField(default=10, max_length=1000),
            preserve_default=False,
        ),
    ]
