# Generated by Django 6.1 on 2026-09-07 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='table_number',
            field=models.CharField(default=2, max_length=10),
            preserve_default=False,
        ),
    ]
