# Generated by Django 6.1 on 2026-09-07 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customer_table_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='encrypted_phone',
            field=models.CharField(default=6, max_length=1000),
            preserve_default=False,
        ),
    ]
