# Generated by Django 6.1 on 2026-09-12 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_customer_encrypted_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='table_number',
        ),
    ]
